# SPDX-License-Identifier: MIT
"""STRtree-based intersection detection — v0.2 speedup backend.

Replaces the v0.1 O(n²) bbox enumeration with a Sort-Tile-Recursive R-tree
(via Shapely / GEOS).  The candidate-pair list is generated by querying each
segment's bounding box against the tree; the final parametric intersection
test is the same vectorised NumPy code used by the pairwise backend.

Complexity:

* Build: O(n log n)
* Query (per segment): O(log n + c) where c is the number of segments whose
  bboxes overlap that segment's bbox.
* Total candidate generation: O(n log n + sum_i c_i).  For sparse inputs
  (road / hydro networks) this is O(n log n + k) where k is the number of
  reported intersections; for dense inputs it degrades toward O(n²) but
  with a much smaller constant than the pairwise enumeration.

Robustness:

* GEOS-backed STRtree handles all the degeneracies (coincident endpoints,
  vertical segments, simultaneous events) that derail a from-scratch
  Bentley-Ottmann implementation.
"""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

_INTERIOR = 1e-9  # match _intersect.py


def find_intersections_strtree(
    segments: NDArray[np.float64],
    bboxes: NDArray[np.float64],  # noqa: ARG001
) -> list[tuple[int, int, float, float]]:
    """STRtree-driven interior-interior intersection detection.

    Output format and semantics are identical to
    :func:`line_noder._intersect.find_intersections`.

    Raises
    ------
    ImportError
        If Shapely is not installed.  Use ``method='pairwise'`` (the default
        v0.1 backend) when running without optional dependencies.
    """
    try:
        from shapely import STRtree
        from shapely.geometry import LineString
    except ImportError as exc:  # pragma: no cover
        raise ImportError(
            "method='strtree' requires shapely. "
            "Install with: pip install 'line-noder[geo]'"
        ) from exc

    n = len(segments)
    if n < 2:
        return []

    # Build LineString geometries and the STRtree index.
    lines = [
        LineString([(float(s[0, 0]), float(s[0, 1])),
                    (float(s[1, 0]), float(s[1, 1]))])
        for s in segments
    ]
    tree = STRtree(lines)

    # Query the tree once with the full set of geometries.  shapely returns
    # a (2, n_pairs) array of (input_index, tree_index) candidate pairs.
    pair_arr = tree.query(lines, predicate="intersects")
    if pair_arr.size == 0:
        return []

    # Filter to i < j and drop self-pairs.
    qi = pair_arr[0]
    qj = pair_arr[1]
    keep = qi < qj
    ci = qi[keep]
    cj = qj[keep]
    if len(ci) == 0:
        return []

    # Vectorised parametric intersection on the candidate pairs — identical
    # arithmetic to the pairwise backend so output is bit-identical on
    # non-degenerate inputs.
    p0 = segments[ci, 0]
    p1 = segments[ci, 1]
    q0 = segments[cj, 0]
    q1 = segments[cj, 1]

    rv = p1 - p0
    sv = q1 - q0
    rxs = rv[:, 0] * sv[:, 1] - rv[:, 1] * sv[:, 0]
    non_parallel = np.abs(rxs) > 1e-10  # parallel tolerance
    if not np.any(non_parallel):
        return []

    idx = np.where(non_parallel)[0]
    ac = q0[idx] - p0[idx]
    t = (ac[:, 0] * sv[idx, 1] - ac[:, 1] * sv[idx, 0]) / rxs[idx]
    u = (ac[:, 0] * rv[idx, 1] - ac[:, 1] * rv[idx, 0]) / rxs[idx]

    interior = (
        (t > _INTERIOR) & (t < 1.0 - _INTERIOR) &
        (u > _INTERIOR) & (u < 1.0 - _INTERIOR)
    )

    results: list[tuple[int, int, float, float]] = []
    for k in np.where(interior)[0]:
        orig = idx[k]
        results.append((int(ci[orig]), int(cj[orig]), float(t[k]), float(u[k])))
    return results
